[package]
name = "guessing_game"
version = "0.1.0"
authors = ["Nagendra Puthane <32806577+nagendraputhane@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"
colored = "2.0.0"